# -*- coding: utf-8 -*-
"""img-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hA_9kn3rdjFZQclkDWaJm1ERAp_4yyFU
"""

import tensorflow as tf
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import datasets,layers,models

(training_images,training_labels),(testing_images,testing_labels)=datasets.cifar10.load_data()
training_images,training_images=training_images/ 255,testing_images /255

class_names=['plane','Car','Bird','Deer','Dog','Frog','Horse','ship','Truck']

for i in range(16):
    plt.subplot(4,4,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.imshow(training_images[i], cmap=plt.cm.binary)
    plt.axis('off')
    plt.show()